<title>  Home </title>
<main class="container-app">
	<h1> DimDim </h1>
	<div class="box-user">
		<div id="btns-home" class="d-flex justify-content-center flex-direction-column mt-5">
			<div class="w-80">
				<input type="submit" id="btnHomeLogin" class='buttom ' value="Login">
				<input type="submit" id="btnHomeRegister" class='buttom' value="Registro" >
			</div>
		</div>
		<div class='fhome d-flex justify-content-center pt-5'>
			<p> Gerindo sua vida com mais controle.</p>
		</div>
	</div>
</main>

