<main >
	<div class="container-app flex-column d-flex justify-content-center">
		
		<h2> Login </h2>
		
		<div class='box-user '>
			<input type='text' name='login' id='login' placeholder='Login'>
			<input type='password' name='password' id='password' placeholder='Senha'>
			<input type='submit' name='singin' id='singin' value='Entrar'>
			<p>Seu primeiro acesso? <a id="register" href="register">Registre-se</a></p>
		</div>
	</div>	
</main>
	
