<html lang="pt">
  <head>
    <title>Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <script
        src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
        crossorigin="anonymous">
    </script>
    </head>
  <body>
      <h1>DimDim</h1>
      <div id='box-user'>
        <input type='text' name='login' id='login' placeholder='Login'>
        <input type='password' name='password' id='password' placeholder='Senha'>
        <input type='submit' name='singin' id='singin' value='Entrar'>
        <p>Seu primeiro acesso? <a id="register">Registre-se</a></p>
      </div>
  </body>
  <footer>
    </footer>
  </html>
