<main class="container-app">
	<form id='registerUser'>
		<h2>Register</h2>
		<div class="box-user">
			<a href='home'><img id='back-page' src=''/></a>
			<input type='text' name='loginUser' id='loginUser' placeholder='Login'>
			<input type="text" name="nameUser" id="nameUser" placeholder="Seu nome">
			<input type='password' name='passwordUser' id='passwordUser' placeholder='Senha'>
			<input type='text' name='keySecrect' id='keySecrect' placeholder='Senha do cofre'>
			<input type='submit' name='registerUser' id='registerUser' value='Registrar'>
		</div>
  </form>
</main>
